apiVersion: apps/v1
kind: Deployment
metadata:
  name: fracture-airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fracture-airflow
  template:
    metadata:
      labels:
        app: fracture-airflow
    spec:
      containers:
        - name: airflow
          image: TU_USUARIO_DOCKER/fracture-airflow:latest
          ports:
            - containerPort: 8080
          env:
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "False"
            - name: AIRFLOW__CORE__EXECUTOR
              value: "SequentialExecutor"
